import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import Footer from "./components/layouts/footer/Footer";
import Nav from "./components/layouts/nav/Nav";
import "./globals.css";
import "aos/dist/aos.css";
import Script from "next/script";
import AOSProvider from "./AOSProvider";
import WsSocket from "@/context/WsSocket";

const cairo = Cairo({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://unpkg.com/aos@2.3.1/dist/aos.css"
          rel="stylesheet"
        ></link>
      </head>
      <body dir="rtl" className={`${cairo.className}`}>
        <Nav />
        <WsSocket>{children}</WsSocket>
        <Footer />
        <AOSProvider />
      </body>
    </html>
  );
}
