import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import Footer from "./components/layouts/footer/Footer";
import Nav from "./components/layouts/nav/Nav";
import "./globals.css";
import ProgressLayOut from "./components/ProgressLayOut";

const cairo = Cairo({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body dir="rtl" className={`${cairo.className}`}>
        <ProgressLayOut>
          <Nav />
          {children}
          <Footer />
        </ProgressLayOut>
      </body>
    </html>
  );
}
